kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: topolvm-blk-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: topolvm-provisioner
  volumeMode: Block 
