kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: topolvm-fs-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: topolvm-provisioner
