apiVersion: v1
kind: Pod
metadata:
  name: topolvm-fs-pvc-pod
spec:
  containers:
  - name: volume-test
    image: ubuntu
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true  
    command: ["/bin/sleep"]
    args: ["3600"]
    volumeMounts:
    - mountPath: /topolvm-fs-pvc
      name: topolvm-fs-pvc
  volumes:
  - name: topolvm-fs-pvc
    persistentVolumeClaim:
      claimName: topolvm-fs-pvc
