apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-blk-vol
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: harvester
  dataSource:
    apiGroup: snapshot.storage.k8s.io  
    kind: VolumeSnapshot
    name: snapshot-blk-vol
  volumeMode: Block