apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: os-vol
  namespace: demo
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-image-hnblz
  volumeMode: Block
