kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: demo
  name: lh-fs-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: 1rep
