apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-workbench
  namespace: build
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-workbench
  template:
    metadata:
      labels:
        app: ubuntu-workbench
    spec:
      # 1️⃣ keep host user-namespace (default)
      hostUsers: true
      # 2️⃣ tell containerd “just chown everything root:0”
      securityContext:
        fsGroup: 2000

      containers:
      - name: workbench
        image: webberhuang/workbench:latest
        imagePullPolicy: Always
        command: ["/usr/bin/dockerd"]
        args: ["--host=unix:///var/run/docker.sock",
               "--host=tcp://0.0.0.0:2375"]
        env:
          - name: DOCKER_TLS_CERTDIR
            value: ""
        securityContext:
          privileged: true
        volumeMounts:
          - name: workspace
            mountPath: /workspace
          - name: docker-graph
            mountPath: /var/lib/docker
          - name: docker-config
            mountPath: /root/.docker
            readOnly: true
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: workbench-src-pvc
        - name: docker-graph
          persistentVolumeClaim:
            claimName: workbench-docker-pvc
        - name: docker-config
          secret:
            secretName: dockerhub-credentials
            defaultMode: 0400
