apiVersion: v1
kind: Pod
metadata:
  name: topolvm-blk-pvc-pod
  namespace: default
spec:
  containers:
  - name: volume-test
    image: ubuntu
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true  
    command: ["/bin/sleep"]
    args: ["3600"]
    volumeDevices:
    - devicePath: /dev/topolvm-blk-pvc
      name: topolvm-blk-pvc
  volumes:
    - name: topolvm-blk-pvc
      persistentVolumeClaim:
        claimName: topolvm-blk-pvc
