apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol1
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: harvester
  volumeMode: Block

