apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: backup-fs-vol
  namespace: default
spec:
  volumeSnapshotClassName: harvester-backup
  source:
    volumeSnapshotContentName: backup-fs-vol-vsc