apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lh-pvc-fs-rwx
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-rwx