apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: backup
  name: lh-pvc-fs
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: 1rep