apiVersion: v1
kind: Service
metadata:
  name: lh-share-manager-headless
  namespace: longhorn-system
spec:
  clusterIP: None
  selector:
    longhorn.io/share-manager: pvc-d3fad61a-5e8b-44cf-af76-1ac52724dc01
  ports:
  - name: nfs
    port: 2049
    targetPort: 2049
    protocol: TCP