apiVersion: v1
kind: Service
metadata:
  name: lh-share-manager-svc
  namespace: longhorn-system
spec:
  selector:
    longhorn.io/share-manager: pvc-xxxx
  ports:
  - name: nfs
    port: 2049
    targetPort: 2049
    protocol: TCP