apiVersion: v1
kind: Pod
metadata:
  name: n1
  namespace: default
spec:
  affinity: {}
  containers:
  - image: nginx:latest
    imagePullPolicy: IfNotPresent
    name: container-0
    volumeMounts:
    - mountPath: /data
      name: vol-ruvyw
  volumes:
  - name: vol-ruvyw
    persistentVolumeClaim:
      claimName: v1