apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: harvester
    meta.helm.sh/release-namespace: harvester-system
    objectset.rio.cattle.io/id: default-mcc-harvester-cattle-fleet-local-system
  creationTimestamp: "2026-01-08T03:56:40Z"
  labels:
    app.kubernetes.io/component: apiserver
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: harvester
    app.kubernetes.io/part-of: harvester
    app.kubernetes.io/version: v1.7.0
    helm.sh/chart: harvester-1.7.0
    helm.sh/release: harvester
    objectset.rio.cattle.io/hash: e852fa897f5eae59a44b4bfe186aad80b10b94b3
  name: harvesterhci.io:csi-driver
  resourceVersion: "8124179"
  uid: 2be450e7-6d4d-443e-a2d9-772bcc2c8f87
rules:
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  - volumeattachments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - harvesterhci.io
  resources:
  - networkfilesystems
  - networkfilesystems/status
  - pvcbackups
  - pvcrestores
  verbs:
  - '*'
- apiGroups:
  - harvesterhci.io
  resourceNames:
  - csi-online-expand-validation
  - csi-driver-config
  resources:
  - settings
  verbs:
  - get
  - list
- apiGroups:
  - longhorn.io
  resources:
  - volumes
  - volumes/status
  verbs:
  - get
  - list
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  - volumesnapshotcontents
  - volumesnapshotclasses
  - volumesnapshots/status
  - volumesnapshotcontents/status
  verbs:
  - '*'
